apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-app
  namespace: default
spec:
  replicas: 1 # 1 реплика экономит ресурсы AWS и упрощает демонстрацию логов комиссии
  selector:
    matchLabels:
      app: helpdesk-app
  template:
    metadata:
      labels:
        app: helpdesk-app
    
    spec:
      containers:
        - name: app
          # Пайплайн GitHub Actions сам заменит эту строчку на ваш Docker Hub репозиторий с нужным тегом
          image: your-dockerhub-username/helpdesk-app:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 # Порт запуска Flask/Gunicorn внутри контейнера

          
          # Переносим настройки из вашего блока `web` и `.env` сюда напрямую
          env:
            - name: DB_HOST
              value: "10.0.1.89"       # Приватный IP адрес вашей нативной базы на EC2
            - name: DB_USER
              value: "support_user"    # Значение из POSTGRES_USER в docker-compose
            - name: DB_PASSWORD
              value: "support_pass"    # Значение из POSTGRES_PASSWORD в docker-compose
            - name: DB_NAME
              value: "support_db"      # Значение из POSTGRES_DB в docker-compose

---
apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service
  namespace: default
spec:
  type: LoadBalancer # AWS автоматически создаст Classic/Network Load Balancer
  ports:
  - port: 80         # Внешний порт для доступа из браузера (http://<IP_балансировщика>)
    targetPort: 8000 # Внутренний порт, на который перенаправляется трафик в контейнер
  selector:
    app: helpdesk-app
