apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-app
  namespace: default
  labels:
    app: helpdesk-app
    Project: fs_support_app
spec:
  replicas: 1 # Минимизирует потребление ресурсов t3.micro и упрощает демонстрацию логов
  selector:
    matchLabels:
      app: helpdesk-app
  template:
    metadata:
      labels:
        app: helpdesk-app
    spec:
      containers:
        - name: app
          # Строка ниже автоматически модифицируется пайплайном GitHub Actions
          image: your-dockerhub-username/helpdesk-app:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 # Порт, на котором Flask/Gunicorn слушает трафик внутри контейнера

          env:
            - name: DB_HOST
              value: "10.0.1.89" # Статический приватный IP вашей нативной базы на EC2
            - name: DB_PORT
              value: "5432"

            # Безопасный импорт авторизационных данных из secret.yaml
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secret
                  key: DB_NAME

          # Проверка доступности (Healthcheck) приложения для демонстрации надежности перед комиссией
          livenessProbe:
            httpGet:
              path: /health # Убедитесь, что этот роут возвращает HTTP 200 в коде Flask
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          # Лимиты ресурсов защищают ноды кластера от перегрузки
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
