apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
  labels:
    app: helpdesk-app
    Project: fs_support_app
spec:
  type: LoadBalancer 
  selector:
    app: helpdesk-app 
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8000 
