apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: default
  labels:
    app: zabbix-agent
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:ubuntu-7.0-latest
          env:
            - name: ZBX_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secret
                  key: ZABBIX_IP
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: ZBX_ACTIVE_ALLOW
              value: "true"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_STARTAGENTS
              value: "3"
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZBX_HOSTMETADATA
              value: "Linux AWS EC2"
            - name: ZBX_LISTENPORT
              value: "10050"
          ports:
            - containerPort: 10050
              hostPort: 10050
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      tolerations:
        - operator: Exists