---
# Общие глобальные переменные для конфигурации ОС и ПО
ansible_python_interpreter: /usr/bin/python3

# Реквизиты PostgreSQL для подключения целевого Flask приложения
db_name: "fs_support_db"
db_user: "db_user"
db_password: "{{ lookup('env', 'DB_PASSWORD') }}"

# Реквизиты репликации
replication_password: "{{ lookup('env', 'REPLICATION_PASSWORD') }}"