[aws_zabbix_servers]
zabbix-server ansible_host=13.60.198.13 ansible_user=ubuntu

[app_databases]
app-database ansible_host=10.0.1.100 ansible_user=ubuntu

[app_databases:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyCommand="ssh -W %h:%p -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@13.60.198.13"'

[all:vars]
ansible_ssh_private_key_file=""
ansible_python_interpreter=/usr/bin/python3
