---
# ansible/site.yml
# Главный оркестратор развертывания инфраструктуры

# Шаг 1: Настраиваем сервер мониторинга Zabbix (Бастион)
- name: Import Zabbix deployment configuration
  import_playbook: deploy-zabbix.yml

# Шаг 2: Настраиваем PostgreSQL в приватной подсети
- name: Import PostgreSQL deployment configuration
  import_playbook: deploy-postgre-db.yml
