name: Cloud Ansible Deployment

# Пайплайн запускается автоматически при любом push в ветку main
on:
  push:
    branches: [ "main" ]

jobs:
  configure-aws-infrastructure:
    runs-on: ubuntu-latest # Быстрая и чистая виртуалка в облаке GitHub

    steps:
    # 1. Скачиваем актуальный код вашего репозитория на раннер GitHub
    - name: Checkout repository code
      uses: actions/checkout@v4

    # 2. Извлекаем секретный ключ из GitHub Secrets и регистрируем в памяти агента GitHub
    - name: Set up SSH Agent Forwarding
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Запускаем конфигурацию через Ansible в облаке GitHub
    - name: Run Ansible Playbook inside GitHub Cloud
      env:
        # Принудительно отключаем интерактивные вопросы yes/no про новые хосты
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        # Переходим в папку, где лежат ваши плейбуки и инвентарь
        cd ansible/

        # Запускаем site.yml и принудительно отключаем мультиплексирование сокетов
        ansible-playbook -i inventory.ini site.yml \
          --ssh-common-args="-o ControlMaster=no -o ControlPersist=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
